# Generated by Django 3.0.2 on 2020-04-01 00:36

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_youtube_result_ten_avg_visit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='writer',
            field=models.CharField(default=builtins.id, max_length=10),
            preserve_default=False,
        ),
    ]
