# Generated by Django 3.0.2 on 2020-04-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_record_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='writer',
        ),
    ]
