# Generated by Django 3.0.2 on 2020-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_record_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='writer',
            field=models.CharField(default='default_id', max_length=10),
            preserve_default=False,
        ),
    ]
