# Generated by Django 3.0.2 on 2020-04-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_record_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='writer',
            field=models.CharField(default='default_id', max_length=10),
        ),
    ]
